### ISSUE TITLE
Sensor_msgs/PointCloud2

### ISSUE THREAD

**Issue by robotsorcerer** [tuftsBaxter/ROS-for-LabVIEW-Software#2]
Hello Guys,

Thanks for this ROS integration .
Do you have a Sensor_msgs/PointCloud2 vi to parse ROS PointCloud2 messages? I see your code has the sensor_msgs/PointCloud vi but I tried this and it did not seem to work with PointCloud2 messages. The x, y, and z fields are not updated.

Would appreciate your response. 
Thanks!

**Comment by wcrooks** [comment]
Hi lakehanne,

Looks like we currently don't have that. The [PointCloud](http://docs.ros.org/api/sensor_msgs/html/msg/PointCloud.html) VI won't work for [PointCloud2](http://docs.ros.org/api/sensor_msgs/html/msg/PointCloud2.html) because they're sending different data types across (see links). You can create your own using the parse building blocks provided (if you open up parse_point_cloud.vi, you can see how we did that for Sensor_msgs/PointCloud). I can update the files to include a prebuilt VI for that by the weekend.

Hope that helps!
Whitney

**Comment by robotsorcerer** [comment]
Hey @wcrooks , thanks for the feedback. I am looking forward to your updated push over the weekend.

**Comment by wcrooks** [comment]
It's up now. Let me know how it works.
