### ISSUE TITLE
RIO with Separate Master Build

### ISSUE THREAD

**Issue by robotsorcerer** [tuftsBaxter/ROS-for-LabVIEW-Software#3]
Hey, 

Trust you are doing well. I can't get the ROSRIO to build on myRIO1900. In your documentation, you mentioned that if one intends to deploy ROSForLabVIEW on myRIO with a different master, one has to deploy your shipped build on the remote RIO first of all, otherwise your codes would not work. Well, here I am 4 hours after unsuccessfully trying to do that and all I've got to show is this attached png file. No description or anything like that whatsoever. 

Would you be kind enough to look into this issue please? Thanks!

![rosforrio](https://cloud.githubusercontent.com/assets/8429860/19630323/2e434d94-994e-11e6-84fc-5010574df555.png)

**Comment by wcrooks** [comment]
Hi lakehanne,

I want to double check that you're using the latest build (which I assume you are because it includes PointCloud2) because there was an error in a previous build that caused that error. It happens when a file name in the source distribution is too long. We solved that problem by deleting our prebuilt source distribution from our code. So you now have to follow the instructions to create your own source distribution.

If you downloaded ROS for LabVIEW a few months ago, you might want to try deleting it and reinstalling a clean build.

If this doesn't help, can you give me your operating system and LabVIEW version, and I'll try to replicate it on the same or a similar system.

Thanks!

**Comment by robotsorcerer** [comment]
I am using LabVIEW 2015 (32-bit) on a Windows 10 (64-bit) machine. I cloned the ROS for LabVIEW repo  about two weeks ago. My RIO runs LabVIEW real-time 2015 and it is wirelessly connected to the machine where my `roscore` is deployed. Hopefully, you can reproduce the problem.

Thanks!

**Comment by robotsorcerer** [comment]
I just cloned the repo all over again and rebuilt and I am seeing the same errors.
It's always complaining about incorrect vi paths. Last evening, I tried to manually specify all the paths but was left with 6 paths that were not in the original repo. 

![new_errors](https://cloud.githubusercontent.com/assets/8429860/19695985/db5b8142-9aaa-11e6-8efb-46630d370656.png)

Please look into these when you can. Thanks!

**Comment by lakehanne** [comment]
I am on Windows 10 and using LabVIEW 2015. 

I cloned the codebase from your github repo a few weeks ago (about 3 weeks).

Sincerely,
Lekan

**Comment by wcrooks** [comment]
Hi Lekan, I'm having trouble reproducing your build error and your missing files error. From what I can tell from your file path, the reason you had to resolve so many conflicts is that you have put the ROS-for-LabVIEW-Software folder in the user.lib instead of the ROS for LabVIEW Software folder contained within the download. (Updating the ReadMe to make this more obvious.) Normally when you build the source distribution with a fresh install, you would have to resolve a few conflicts (relating to us saving the software in 2012), but you shouldn't have to manually correct every file.

Both the files that I can see from your screenshot (DigitalIOWrapper.vi and DigitalIOCommand.vi) are on github and were in present in the files I downloaded to two separate computers.

As for the build error. Where are you saving your source distribution? If you are saving it anywhere within the ROS for LabVIEW Software folder that is located in the user.lib, that is what is causing your build error. You should delete those files and recreate them in another location outside of your program files.

If that's not the problem and since I can't reproduce this, it would be helpful to see your project and the files you have downloaded.

Whitney

**Comment by robotsorcerer** [comment]
> From what I can tell from your file path, the reason you had to resolve so many conflicts is that you have put the ROS-for-LabVIEW-Software folder in the user.lib instead of the ROS for LabVIEW Software folder contained within the download. 

Pardon my error but this was not clear from the README.

> As for the build error. Where are you saving your source distribution?

I am saving the source distribution within `My Documents` folder on Windows.

> If that's not the problem and since I can't reproduce this, it would be helpful to see your project and the files you have downloaded.

Actually, the project is indexed here on github. You may clone the project and its associated ROS for LabVIEW dependency [here](https://github.com/SeRViCE-Lab/RAL-Codes).

Thanks. I will try the suggestions you have mentioned. Also, if you find an anomaly in the code I have provided above, would be glad to hear your opinion. 

Thanks again!

**Comment by wcrooks** [comment]
I've updated the readme so it's hopefully more obvious now. Let me know if you have a suggestion for a way to make it more apparent.

I'm hoping that by putting the embedded folder into the user.lib instead of the downloaded folder will help resolve the issue (or at least part of the issue). I've gotten Error 6 before when creating source distributions where file paths have exceeded 255 characters. You could try saving the build to a different folder (say in your user folder) and see if you get the same error.

**Comment by robotsorcerer** [comment]
Thanks a lot Whitney!

I got it to build by downloading the whole repo as a zipped master, unzippping and moving the `ROS for LabVIEW` folder to `user.lib`.  I earlier used the `git client` on bash for Windows in cloning straight to `user.lib` and hence the issues I had with my builds. 

Thank you for your time and I hope you continue to stay frosty in the Boston weather :stuck_out_tongue_closed_eyes:

**Comment by wcrooks** [comment]
Ah okay. I will make a note of that in the ReadMe and the RIO help!
